language: node_js
os:
  - linux

node_js:
  - stable

cache:
  directories:
  - node_modules

script:
  - "node ./src/scripts/fetchGitActivity"
  - "npm run build"

  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: false
  target_branch: gh-pages
  on:
    branch: master  